version: "3"

services:
  kafka:
    image: rnkoaa/kafka
    ports:
      - "9092:9092"
    networks:
      - order-service
  kafka-connect:
    image: rnkoaa/kafka-connect:6.2.1
    ports:
      - "8081:8081"
    environment:
      - "CONNECT_BOOTSTRAP_SERVERS=kafka:9092"
    networks:
      - order-service
  
networks:
  order-service: 

