version: "3"

services:
  kafka:
    image: rnkoaa/kafka-kraft:3
    ports:
      - "9092:9092"
    networks:
      - order-service
    environment:
      KRAFT_CONTAINER_HOST_NAME: kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # kafka-connect:
  #   image: rnkoaa/kafka-connect:6.2.1
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - "CONNECT_BOOTSTRAP_SERVERS=kafka:9092"
  #   networks:
  #     - order-service
  #   depends_on:
  #     - kafka
  
networks:
  order-service: 

